steps:
  - id: 'Copy env.example to .env'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'cp .env.example .env'

  - id: 'Build with Docker Compose'
    name: 'docker/compose:1.29.2'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'docker-compose -f docker-compose.yml build'

 - id: 'Push'
    name: 'docker/compose:1.29.2'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker tag app:latest ${_IMAGE_NAME}
        docker push ${_IMAGE_NAME}

images:
  - '${_IMAGE_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

substitutions:
  _IMAGE_NAME: '${_ARTIFACT_REGISTRY_LOCATION}/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_DOCKER_IMAGE_NAME}:${SHORT_SHA}'

tags:
  - swgcc-thesis
