steps:
  - id: 'Copy env.example to .env'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'cp env.example .env'

  - id: Build
    name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t',
      '${_IMAGE_NAME}',
      '.'
    ]

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_IMAGE_NAME}'

images:
  - '${_IMAGE_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

substitutions:
  _IMAGE_NAME: '${_ARTIFACT_REGISTRY_LOCATION}/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPOSITORY}/${_DOCKER_IMAGE_NAME}:${SHORT_SHA}'

tags:
  - swgcc-thesis
