steps:
  - id: 'Build app image'
    name: 'docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t us-central1-docker.pkg.dev/${PROJECT_ID}/swgcc-app:${SHORT_SHA} -f Dockerfile.app .

  - id: 'Build vite image'
    name: 'docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t us-central1-docker.pkg.dev/${PROJECT_ID}/swgcc-vite:${SHORT_SHA} -f Dockerfile.vite .

  - id: 'Push app image'
    name: 'docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push us-central1-docker.pkg.dev/${PROJECT_ID}/swgcc-app:${SHORT_SHA}

  - id: 'Push vite image'
    name: 'docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push us-central1-docker.pkg.dev/${PROJECT_ID}/swgcc-vite:${SHORT_SHA}

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/swgcc-app:${SHORT_SHA}'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/swgcc-vite:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

substitutions:
  _IMAGE_NAME_APP: 'us-central1-docker.pkg.dev/${PROJECT_ID}/swgcc-app:${SHORT_SHA}'
  _IMAGE_NAME_VITE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/swgcc-vite:${SHORT_SHA}'
