# Dockerfile.vite
FROM node:18-alpine

# Establecer el directorio de trabajo
WORKDIR /var/www/html

# Copiar los archivos necesarios
COPY package.json package-lock.json ./
COPY resources resources/
COPY vite.config.js ./

# Instalar dependencias de Node.js
RUN npm install

# Exponer el puerto que Vite utiliza
EXPOSE 5173

# Comando para iniciar Vite en modo desarrollo
CMD ["npm", "run", "dev"]
